function generateReport() {
  const course = document.getElementById('courseName').value.trim();
  const url = document.getElementById('pageUrl').value.trim();
  const builder = document.getElementById('courseBuilder').value.trim();
  const designer = document.getElementById('designerName').value.trim();
  const notes = document.getElementById('notes').value.trim();

  const sliders = document.querySelectorAll('input[type="range"]');
  const ratings = [];

  sliders.forEach(slider => {
    const label = slider.getAttribute('data-label');
    const value = parseInt(slider.value);
    let desc = '';
    switch (value) {
      case 0: desc = '❌ Not met'; break;
      case 1: desc = '⚠️ Baseline'; break;
      case 2: desc = '⬆️ Enhanced'; break;
      case 3: desc = '✅ Best practice'; break;
    }
    ratings.push(`${label}: ${desc} (Score ${value}/3)`);
  });

  const output = `
Canvas UX & Course Quality Summary

This report was generated by ${designer || '[Designer Name]'} for the course "${course || '[Course Name]'}", led by ${builder || '[Course Builder]'}.

Page reviewed: ${url || '[Page URL]'}

Each criterion below was rated on a scale from 0–3. These ratings help identify areas of strength and potential improvement in UX and course design.

🧩 Ratings:
${ratings.map(r => '- ' + r).join('\n')}

📝 Notes:
${notes || '[No additional notes provided]'}
`;

  document.getElementById('output').value = output.trim();
}

function copyReport() {
  const text = document.getElementById('output');
  text.select();
  document.execCommand('copy');
}

function downloadPDF() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const logo = new Image();
  logo.src = 'AU logo primary_white.png';

  logo.onload = () => {
    doc.setFillColor(22, 12, 80);
    doc.rect(0, 0, 210, 35, 'F');
    doc.addImage(logo, 'PNG', 10, 6, 40, 20);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Canvas UX & Course Quality Summary", 105, 25, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');

    const text = document.getElementById('output').value;
    const lines = doc.splitTextToSize(text, 180);
    let y = 45;

    lines.forEach(line => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 15, y);
      y += 7;
    });

    doc.save('UX-course-review.pdf');
  };
}
